version: '2'
services:
  maven:
    build: maven
    volumes:
      - web_app:./target
    command: ls -l ./target
  tomcat:
    image: tomcat:8.0
    volumes:
      - web_app:/web_app
      #- ./tomcat/ROOT.xml:/usr/share/tomcat8/conf/Catalina/localhost/ROOT.xml
      #- ./tomcat/:/webapps
    command: cp -r /web_app/hello-1.0 /usr/local/tomcat/webapps/
    ports:
      - "85:8080"
volumes:
  web_app:

