version: '2'
services:
  maven:
    build: maven
    volumes:
      - web_app:/boxfuse-sample-java-war-hello
  tomcat:
    build: tomcat
    environment:
      - CATALINA_BASE=/usr/share/tomcat8/
    volumes:
      - web_app:/web_app
      - ./tomcat/ROOT.xml:/usr/share/tomcat8/conf/Catalina/localhost/ROOT.xml
    ports:
      - "85:8080"
volumes:
  web_app:

