version: '2'
services:
  maven:
    build: maven
    volumes:
      - web_app:/boxfuse-sample-java-war-hello
  tomcat:
    build: tomcat
    environment:
      - CATALINA_HOME=/web_app
      - CATALINA_BASE=/var/lib/tomcat8
    volumes:
      - web_app:/usr/share/tomcat8/
    ports:
      - "85:8080"
volumes:
  web_app:

