version: '2'
services:
  maven:
    build: maven
    volumes:
      - web_app:/boxfuse-sample-java-war-hello/

  tomcat:
    image: tomcat:8.0
    volumes:
      - web_app:/web_app
    command: bash -c "cp -r /web_app/target/hello-1.0 /usr/local/tomcat/webapps/ && ls -l /usr/local/tomcat/webapps"
    entrypoint: ["catalina.sh", "run"]
    ports:
      - "85:8080"
    depends_on:
      - maven
volumes:
  web_app:

