version: '2'
services:
  maven:
    build: maven
    volumes:
      - web_app:/boxfuse-sample-java-war-hello/target/
  tomcat:
    image: tomcat:8.0
    volumes:
      - web_app:/usr/local/tomcat/webapps/
      # - ./tomcat/ROOT.xml:/usr/share/tomcat8/conf/Catalina/localhost/ROOT.xml
      #- ./tomcat/:/webapps
    ports:
      - "85:8080"
volumes:
  web_app:

