version: '2'
services:
  maven:
    build: maven
    volumes:
      - web_app:/boxfuse-sample-java-war-hello
  tomcat:
    build: tomcat
    environment:
      - ENV CATALINA_BASE=/web_app
    volumes:
      - web_app:/web_app
    ports:
      - "85:8080"



